# Generated by Django 5.0.3 on 2024-03-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_alter_label_options'),
        ('tasks', '0003_alter_membership_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='label_set',
            field=models.ManyToManyField(blank=True, through='tasks.Membership', to='labels.label'),
        ),
    ]
